---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: beta
    namespace: dolittle
  spec:
    template:
      metadata:
        labels:
          app: beta
          name: beta
      spec:
        containers:
        - name: beta
          image: dolittle/beta
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: beta
    namespace: dolittle
    labels:
      app: beta
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      name: beta-port
      protocol: TCP
    selector:
      app: beta
      name: beta
  