backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
logo_url: https://www.dolittle.com/images/Logos/dolittle_positiv_horisontal.svg
media_folder: "hugo/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "header" # Used in routes, e.g., /admin/collections/blog
    label: "Header" # Used in the UI
    folder: "hugo/content/header" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Sub header", name: "subheading", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "employee"
    identifier_field: "name"
    label: "Employee"
    folder: "hugo/content/employee"
    create: true
    fields:
      - {label: "Full name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Start date", name: "publishdate", widget: "date"}
      - label: "Social media"
        name: "some"
        widget: "object"
        hint: "Only the userpart of the URL"
        fields:
          - {label: "Twitter handle", , name: "twitter", widget: "string", required: false}
          - {label: "LinkedIn username", name: "linkedin", widget: "string", required: false}
          - {label: "GitHub username", name: "github", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean"}
  - name: "introitem"
    label: "Intro item"
    folder: "hugo/content/introitem"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Instruction", name: "instruction", widget: "text", required: false}
      - {label: "Background image", name: "bgImage", widget: "image", required: false}
      - {label: "Icon class", name: "icon", widget: "string", hint: "Class name given from Simple Line Icons. (Sorry about this, it'll be humanized later)"}
      - label: "CTA Button"
        name: "ctaButton"
        widget: "object"
        fields:
          - {label: "URL", name: "url", widget: "string", required: false}
          - {label: "Text", name: "text", widget: "string", required: false}
      - {label: "Order", name: "weight", widget: "number"}
  - name: "introvideo"
    label: "Intro Video"
    folder: "hugo/content/introvideo"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Youtube ID", name: "youtube_id", widget: "string"}
      - {label: "Publish date", name: "publishDate", widget: "date"}
